languageCode = "en-us"
defaultContentLanguage = "en"

baseURL = "https://minified.design/"
title = "Minified Design"
copyright = "© {year} <a href=\"https://minified.design\">Minified Design.</a> All rights reserved."

googleAnalytics = "UA-164160631-1"

theme = "minified"
metaDataFormat = "yaml"

enableRobotsTXT = "true"


[params]

